# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Mozily Blog
email:       'mozily@gmail.com'
description: 'Mozily Blog'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://mozily.github.io' # The base hostname & protocol for your site
twitter:     ''
github:      'https://github.com/mozily'
instagram:   ''
facebook:    ''

markdown:  kramdown
permalink: pretty
paginate:  15

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - server.sh
  - build.sh