name: mozily blog

description: mozily development log

author: mozily

github_username: mozily

email: mozily@gmail.com

disqus_url: https://mozily-github-io.disqus.com
disqus_id: mozily

#google_analytics_id:
